/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("multiproject.kotlin-application-conventions")
}

dependencies {
    implementation(project(":udpsocket"))
    implementation("io.insert-koin:koin-core:3.3.3")
}

application {
    // Define the main class for the application.
    mainClass.set("multiproject.client.AppKt")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}