/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("multiproject.kotlin-application-conventions")
    kotlin("plugin.serialization") version "1.8.10"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":udpsocket"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")
    implementation("io.insert-koin:koin-core:3.3.3")
    implementation("de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv:2.0.0")
    implementation(project(mapOf("path" to ":client")))
}

application {
    // Define the main class for the application.
    mainClass.set("multiproject.server.AppKt")
}
