/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multiproject.resolver

import multiproject.lib.dto.request.RequestDirection
import multiproject.lib.dto.request.RequestDirectionInterpreter
import multiproject.lib.request.Request
import multiproject.lib.request.resolvers.*
import multiproject.lib.udp.SocketAddressInterpreter
import multiproject.lib.udp.UdpConfig
import multiproject.lib.udp.gateway.GatewayUdpChannel
import multiproject.lib.udp.gateway.runGateway
import multiproject.lib.udp.interfaces.OnConnect
import multiproject.lib.udp.interfaces.OnReceive
import org.koin.core.context.GlobalContext.startKoin
import org.koin.core.qualifier.named
import org.koin.dsl.module
import org.koin.java.KoinJavaComponent.inject
import java.net.InetSocketAddress

class App {
    init {
        val module = module {
            single<GatewayUdpChannel>(named("server")) {
                runGateway {
                    receiveCallback = OnReceive {
                        _, address, data -> run {
                            if (data.command == "")
                                return@run;

                            val inetAddress = SocketAddressInterpreter.interpret(address)
                            val request = Request(data);

                            if (RequestDirectionInterpreter.interpret(request.requestDirection) == RequestDirection.FROM_CLIENT) {
                                request.acceptResolver(ClientRequestResolver(this, inetAddress))
                            } else if (RequestDirectionInterpreter.interpret(request.requestDirection) == RequestDirection.FROM_SERVER) {
                                request.acceptResolver(ServerRequestResolver(this, inetAddress))
                            } else {
                                request.acceptResolver(UnknownRequestResolver(this, inetAddress))
                            }
                        }
                    }
                    firstConnectCallback = OnConnect {
                        _, address, data -> run {
                            val request = Request(data);
                            val inetAddress = SocketAddressInterpreter.interpret(address)

                            if (RequestDirectionInterpreter.interpret(request.requestDirection) == RequestDirection.FROM_CLIENT) {
                                request.acceptResolver(ClientFirstRequestResolver(this, inetAddress))
                            } else if (RequestDirectionInterpreter.interpret(request.requestDirection) == RequestDirection.FROM_SERVER) {
                                request.acceptResolver(ServerFirstRequestResolver(this, inetAddress))
                            } else {
                                request.acceptResolver(UnknownRequestResolver(this, inetAddress))
                            }

                            request.acceptResolver(FirstRequestResolver(this, inetAddress));
                        }
                    }
                    bindOn(
                        address = InetSocketAddress(UdpConfig.serverAddress, UdpConfig.serverPort)
                    )
                }
            }
        }
        startKoin {
            modules(
                module
            )
        }
    }
}


fun main() {
    try {
        App()
        val server: GatewayUdpChannel by inject(GatewayUdpChannel::class.java, named("server"))
        server.run()
    } finally {
    }
}