/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lab5kotlin

import lab5kotlin.collection.Collection
import lab5kotlin.collection.exceptions.ValidationFieldException
import lab5kotlin.console.CollectionPrinter
import javax.swing.text.Position

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    var collection: Collection<Human> = Collection<Human>()

    fun createCollection() {
        try {
            val onCreatePosition = mutableMapOf<String, Any?>()
            onCreatePosition["x"] = 1
            onCreatePosition["y"] = 2
            val position = Coordinates(onCreatePosition)
            val onCreateHuman = mutableMapOf<String, Any?>()
            onCreateHuman["id"] = 1
            onCreateHuman["name"] = "Alex"
            onCreateHuman["age"] = 18L
            onCreateHuman["position"] = position;
            onCreateHuman["fatness"] = Fatness.FAT;
            val humanItem = Human(onCreateHuman)
            collection.addItem(humanItem)
        } catch (e: ValidationFieldException) {
            println("Item creation failed!")
            println("Validation failed when processing ${e.field.name} field")
            println("Input value: ${e.validatedValue} must be ${e.field.type} type")
        }
    }

    fun printCollection() {
        val printer = CollectionPrinter()
        printer.print(collection)
    }
}

fun main() {
    val app = App()
    println(app.greeting)
    app.createCollection()
    app.printCollection()
}
